language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - dist: xenial
    - dist: bionic

branches:
  only:
  - master
  - develop
  - ci

notifications:
  email:
    on_success: never

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install
  - python test.py
